'use client';

import { Card } from '@/components/ui/card';
import { Sparkles, CheckCircle, AlertCircle, Lightbulb, Brain } from 'lucide-react';

interface AIInsightsPanelProps {
  summary: string;
  insights: string[];
}

export default function AIInsightsPanel({ summary, insights }: AIInsightsPanelProps) {
  return (
    <Card className="border-border space-y-0 overflow-hidden bg-gradient-to-br from-card via-accent/5 to-card/50 border-2 border-accent/20">
      {/* Header */}
      <div className="p-6 border-b border-accent/20 bg-gradient-to-r from-accent/10 to-transparent">
        <div className="flex items-center gap-3">
          <div className="rounded-lg bg-accent/20 p-2">
            <Brain className="h-5 w-5 text-accent" />
          </div>
          <h3 className="text-lg font-bold text-foreground">AI Security Analysis</h3>
        </div>
      </div>

      <div className="p-6 space-y-6">
        {/* Summary */}
        <div className="space-y-3">
          <h4 className="text-sm font-semibold text-accent flex items-center gap-2">
            <Lightbulb className="h-4 w-4" />
            Executive Summary
          </h4>
          <div className="p-4 rounded-xl bg-accent/5 border border-accent/20 backdrop-blur-sm">
            <p className="text-sm text-foreground leading-relaxed font-medium">{summary}</p>
          </div>
        </div>

        {/* Insights */}
        <div className="space-y-3">
          <h4 className="text-sm font-semibold text-foreground flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-accent" />
            Key Recommendations
          </h4>
          <ul className="space-y-2">
            {insights.map((insight, index) => (
              <li
                key={index}
                className="flex items-start gap-3 p-3 rounded-xl bg-card border border-border/50 text-sm hover:border-accent/40 hover:bg-accent/5 transition-all group"
              >
                <CheckCircle className="h-5 w-5 text-accent flex-shrink-0 mt-0.5 group-hover:scale-110 transition-transform" />
                <span className="text-foreground">{insight}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* AI Disclaimer */}
        <div className="flex items-start gap-3 p-4 rounded-xl bg-muted/30 border border-border/50 text-xs">
          <AlertCircle className="h-4 w-4 text-muted-foreground flex-shrink-0 mt-0.5" />
          <span className="text-muted-foreground leading-relaxed">
            <strong>Disclaimer:</strong> These AI insights are generated by machine learning and should be reviewed and validated by your security team before taking action.
          </span>
        </div>
      </div>
    </Card>
  );
}
